global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'mookies-monitor'

scrape_configs:
  - job_name: 'mookies-server'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9001', 'localhost:9002']
  - job_name: 'mookies-front'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9003']
  - job_name: 'mookies-kitchen'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9004']
