// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/mookies.proto

package mookiespb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id    int32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Price float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	// @inject_tag: db:"category_id"
	CategoryID           int32     `protobuf:"varint,4,opt,name=categoryID,proto3" json:"categoryID,omitempty" db:"category_id"`
	Options              []*Option `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetCategoryID() int32 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *Item) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type Option struct {
	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	// @inject_tag: db:"by_default"
	ByDefault            bool     `protobuf:"varint,3,opt,name=byDefault,proto3" json:"byDefault,omitempty" db:"by_default"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{1}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Option) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Option) GetByDefault() bool {
	if m != nil {
		return m.ByDefault
	}
	return false
}

type Category struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Items                []*Item  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{2}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Menu struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{3}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Order struct {
	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Items  []*Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Total  float32 `protobuf:"fixed32,4,opt,name=total,proto3" json:"total,omitempty"`
	Status string  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// @inject_tag: db:"time_ordered"
	TimeOrdered string `protobuf:"bytes,6,opt,name=time_ordered,json=timeOrdered,proto3" json:"time_ordered,omitempty" db:"time_ordered"`
	// @inject_tag: db:"time_complete"
	TimeComplete         string   `protobuf:"bytes,7,opt,name=time_complete,json=timeComplete,proto3" json:"time_complete,omitempty" db:"time_complete"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{4}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetTimeOrdered() string {
	if m != nil {
		return m.TimeOrdered
	}
	return ""
}

func (m *Order) GetTimeComplete() string {
	if m != nil {
		return m.TimeComplete
	}
	return ""
}

type SubmitOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitOrderRequest) Reset()         { *m = SubmitOrderRequest{} }
func (m *SubmitOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitOrderRequest) ProtoMessage()    {}
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{5}
}

func (m *SubmitOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitOrderRequest.Unmarshal(m, b)
}
func (m *SubmitOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitOrderRequest.Marshal(b, m, deterministic)
}
func (m *SubmitOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitOrderRequest.Merge(m, src)
}
func (m *SubmitOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitOrderRequest.Size(m)
}
func (m *SubmitOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitOrderRequest proto.InternalMessageInfo

func (m *SubmitOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type SubmitOrderResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitOrderResponse) Reset()         { *m = SubmitOrderResponse{} }
func (m *SubmitOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitOrderResponse) ProtoMessage()    {}
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{6}
}

func (m *SubmitOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitOrderResponse.Unmarshal(m, b)
}
func (m *SubmitOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitOrderResponse.Marshal(b, m, deterministic)
}
func (m *SubmitOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitOrderResponse.Merge(m, src)
}
func (m *SubmitOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitOrderResponse.Size(m)
}
func (m *SubmitOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitOrderResponse proto.InternalMessageInfo

func (m *SubmitOrderResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SubscribeToOrderRequest struct {
	Request              string   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToOrderRequest) Reset()         { *m = SubscribeToOrderRequest{} }
func (m *SubscribeToOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToOrderRequest) ProtoMessage()    {}
func (*SubscribeToOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{7}
}

func (m *SubscribeToOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToOrderRequest.Unmarshal(m, b)
}
func (m *SubscribeToOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToOrderRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeToOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToOrderRequest.Merge(m, src)
}
func (m *SubscribeToOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeToOrderRequest.Size(m)
}
func (m *SubscribeToOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToOrderRequest proto.InternalMessageInfo

func (m *SubscribeToOrderRequest) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

type CompleteOrderRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteOrderRequest) Reset()         { *m = CompleteOrderRequest{} }
func (m *CompleteOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CompleteOrderRequest) ProtoMessage()    {}
func (*CompleteOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{8}
}

func (m *CompleteOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteOrderRequest.Unmarshal(m, b)
}
func (m *CompleteOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteOrderRequest.Marshal(b, m, deterministic)
}
func (m *CompleteOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteOrderRequest.Merge(m, src)
}
func (m *CompleteOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CompleteOrderRequest.Size(m)
}
func (m *CompleteOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteOrderRequest proto.InternalMessageInfo

func (m *CompleteOrderRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CompleteOrderResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteOrderResponse) Reset()         { *m = CompleteOrderResponse{} }
func (m *CompleteOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteOrderResponse) ProtoMessage()    {}
func (*CompleteOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{9}
}

func (m *CompleteOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteOrderResponse.Unmarshal(m, b)
}
func (m *CompleteOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteOrderResponse.Marshal(b, m, deterministic)
}
func (m *CompleteOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteOrderResponse.Merge(m, src)
}
func (m *CompleteOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CompleteOrderResponse.Size(m)
}
func (m *CompleteOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteOrderResponse proto.InternalMessageInfo

func (m *CompleteOrderResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type OrdersRequest struct {
	Request              string   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdersRequest) Reset()         { *m = OrdersRequest{} }
func (m *OrdersRequest) String() string { return proto.CompactTextString(m) }
func (*OrdersRequest) ProtoMessage()    {}
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{10}
}

func (m *OrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersRequest.Unmarshal(m, b)
}
func (m *OrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersRequest.Marshal(b, m, deterministic)
}
func (m *OrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersRequest.Merge(m, src)
}
func (m *OrdersRequest) XXX_Size() int {
	return xxx_messageInfo_OrdersRequest.Size(m)
}
func (m *OrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersRequest proto.InternalMessageInfo

func (m *OrdersRequest) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

type OrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdersResponse) Reset()         { *m = OrdersResponse{} }
func (m *OrdersResponse) String() string { return proto.CompactTextString(m) }
func (*OrdersResponse) ProtoMessage()    {}
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{11}
}

func (m *OrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersResponse.Unmarshal(m, b)
}
func (m *OrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersResponse.Marshal(b, m, deterministic)
}
func (m *OrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersResponse.Merge(m, src)
}
func (m *OrdersResponse) XXX_Size() int {
	return xxx_messageInfo_OrdersResponse.Size(m)
}
func (m *OrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersResponse proto.InternalMessageInfo

func (m *OrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a42f9bdfdd6c12cf, []int{12}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Item)(nil), "mookiespb.Item")
	proto.RegisterType((*Option)(nil), "mookiespb.Option")
	proto.RegisterType((*Category)(nil), "mookiespb.Category")
	proto.RegisterType((*Menu)(nil), "mookiespb.Menu")
	proto.RegisterType((*Order)(nil), "mookiespb.Order")
	proto.RegisterType((*SubmitOrderRequest)(nil), "mookiespb.SubmitOrderRequest")
	proto.RegisterType((*SubmitOrderResponse)(nil), "mookiespb.SubmitOrderResponse")
	proto.RegisterType((*SubscribeToOrderRequest)(nil), "mookiespb.SubscribeToOrderRequest")
	proto.RegisterType((*CompleteOrderRequest)(nil), "mookiespb.CompleteOrderRequest")
	proto.RegisterType((*CompleteOrderResponse)(nil), "mookiespb.CompleteOrderResponse")
	proto.RegisterType((*OrdersRequest)(nil), "mookiespb.OrdersRequest")
	proto.RegisterType((*OrdersResponse)(nil), "mookiespb.OrdersResponse")
	proto.RegisterType((*Empty)(nil), "mookiespb.Empty")
}

func init() { proto.RegisterFile("protofiles/mookies.proto", fileDescriptor_a42f9bdfdd6c12cf) }

var fileDescriptor_a42f9bdfdd6c12cf = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x8d, 0x9d, 0x38, 0x69, 0x26, 0x49, 0x7f, 0xbf, 0x6e, 0x0b, 0x98, 0x08, 0x4a, 0x58, 0x44,
	0x15, 0x84, 0x48, 0x51, 0x72, 0x03, 0x7a, 0x40, 0x2d, 0x42, 0x3d, 0x94, 0x20, 0xa7, 0x9c, 0x51,
	0x9c, 0x4c, 0xd1, 0x8a, 0x38, 0x6b, 0xbc, 0xeb, 0x4a, 0xf9, 0x10, 0x7c, 0x29, 0x4e, 0x7c, 0x2c,
	0xb4, 0x63, 0x3b, 0xdd, 0xfc, 0xa9, 0xda, 0x9b, 0x67, 0xe6, 0xbd, 0x99, 0xb7, 0x6f, 0x26, 0x01,
	0x3f, 0x4e, 0xa4, 0x96, 0x57, 0x62, 0x86, 0xea, 0x38, 0x92, 0xf2, 0xa7, 0x40, 0xd5, 0xa3, 0x14,
	0xab, 0xe7, 0x61, 0x1c, 0xf2, 0xdf, 0x0e, 0x54, 0xce, 0x35, 0x46, 0x8c, 0x41, 0x65, 0x3e, 0x8e,
	0xd0, 0x77, 0x3a, 0x4e, 0xb7, 0x1e, 0xd0, 0x37, 0xdb, 0x05, 0x57, 0x4c, 0x7d, 0xb7, 0xe3, 0x74,
	0xbd, 0xc0, 0x15, 0x53, 0x76, 0x00, 0x5e, 0x9c, 0x88, 0x09, 0xfa, 0xe5, 0x8e, 0xd3, 0x75, 0x83,
	0x2c, 0x60, 0x87, 0x00, 0x93, 0xb1, 0xc6, 0x1f, 0x32, 0x59, 0x9c, 0x9f, 0xf9, 0x15, 0x42, 0x5b,
	0x19, 0xf6, 0x1a, 0x6a, 0x32, 0xd6, 0x42, 0xce, 0x95, 0xef, 0x75, 0xca, 0xdd, 0x46, 0x7f, 0xaf,
	0xb7, 0x9c, 0xdf, 0x1b, 0x52, 0x25, 0x28, 0x10, 0xfc, 0x2b, 0x54, 0xb3, 0xd4, 0x56, 0x41, 0x4b,
	0x01, 0xae, 0x2d, 0xe0, 0x09, 0xd4, 0xc3, 0xc5, 0x19, 0x5e, 0x8d, 0xd3, 0x99, 0x26, 0x69, 0x3b,
	0xc1, 0x4d, 0x82, 0x7f, 0x83, 0x9d, 0xd3, 0x5c, 0xcc, 0xbd, 0x1e, 0xf9, 0x12, 0x3c, 0xa1, 0x31,
	0x52, 0x7e, 0x99, 0xc4, 0xfe, 0x67, 0x89, 0x35, 0x46, 0x05, 0x59, 0x95, 0xbf, 0x87, 0xca, 0x05,
	0xce, 0x53, 0x36, 0x58, 0xbe, 0x5e, 0xa0, 0xf2, 0x1d, 0xe2, 0xec, 0x5b, 0x9c, 0x62, 0x76, 0x60,
	0xc1, 0xf8, 0x5f, 0x07, 0xbc, 0x61, 0x32, 0xc5, 0x24, 0x9f, 0xee, 0x2c, 0xa7, 0x17, 0x0a, 0x5d,
	0x4b, 0xe1, 0xfd, 0x14, 0x19, 0x73, 0xb4, 0xd4, 0xe3, 0x19, 0xad, 0xc0, 0x0d, 0xb2, 0x80, 0x3d,
	0x84, 0xaa, 0xd2, 0x63, 0x9d, 0x1a, 0xf3, 0x4d, 0xcb, 0x3c, 0x62, 0xcf, 0xa1, 0xa9, 0x45, 0x84,
	0xdf, 0xa5, 0x91, 0x81, 0x53, 0xbf, 0x4a, 0xd5, 0x86, 0xc9, 0x0d, 0xb3, 0x14, 0x7b, 0x01, 0x2d,
	0x82, 0x4c, 0x64, 0x14, 0xcf, 0x50, 0xa3, 0x5f, 0x23, 0x0c, 0xf1, 0x4e, 0xf3, 0x1c, 0xff, 0x00,
	0x6c, 0x94, 0x86, 0x91, 0xd0, 0xc4, 0x0a, 0xf0, 0x57, 0x8a, 0x4a, 0xb3, 0x23, 0xf0, 0xa8, 0x31,
	0xbd, 0xac, 0xd1, 0xff, 0xdf, 0xde, 0x38, 0xe1, 0xb2, 0x32, 0x7f, 0x03, 0xfb, 0x2b, 0x6c, 0x15,
	0xcb, 0xb9, 0x42, 0x23, 0x3a, 0x41, 0x65, 0xd6, 0x99, 0x6d, 0x2a, 0x8f, 0xf8, 0x00, 0x1e, 0x8d,
	0xd2, 0x50, 0x4d, 0x12, 0x11, 0xe2, 0xa5, 0x5c, 0x99, 0xe8, 0x43, 0x2d, 0xc9, 0x3e, 0x73, 0x4e,
	0x11, 0xf2, 0x23, 0x38, 0x28, 0xd4, 0xae, 0x30, 0xd6, 0xac, 0xe7, 0xc7, 0xf0, 0x60, 0x0d, 0x77,
	0x87, 0x9a, 0x57, 0xd0, 0x22, 0xa0, 0xba, 0x5b, 0xc3, 0x3b, 0xd8, 0x2d, 0xa0, 0x79, 0xd3, 0x2e,
	0x54, 0xc9, 0x82, 0xe2, 0x66, 0x36, 0x2d, 0xca, 0xeb, 0xbc, 0x06, 0xde, 0xa7, 0x28, 0xd6, 0x8b,
	0xfe, 0x09, 0x34, 0xcc, 0xc9, 0x8d, 0x30, 0xb9, 0x36, 0x67, 0xdf, 0x83, 0xda, 0x67, 0xd4, 0x74,
	0x84, 0x36, 0x99, 0xb0, 0x6d, 0xfb, 0x48, 0x0c, 0x84, 0x97, 0xfa, 0x7f, 0x5c, 0x68, 0x52, 0xe7,
	0xa2, 0xc1, 0x17, 0x68, 0x58, 0xe6, 0xb3, 0xa7, 0x16, 0x65, 0x73, 0xa5, 0xed, 0xc3, 0xdb, 0xca,
	0xd9, 0x83, 0x78, 0x89, 0x5d, 0x42, 0x6b, 0xc5, 0x40, 0xf6, 0xcc, 0xfe, 0x1d, 0x6c, 0x59, 0x41,
	0xbb, 0x73, 0x3b, 0x60, 0xd9, 0xf5, 0x02, 0xf6, 0xd6, 0x77, 0xae, 0x18, 0x5f, 0x15, 0xb3, 0xed,
	0x22, 0xda, 0x1b, 0x8e, 0xf2, 0xd2, 0x5b, 0x87, 0x9d, 0x40, 0xf3, 0xe3, 0x44, 0x8b, 0x6b, 0xcc,
	0x3b, 0x6d, 0x5a, 0xf7, 0x78, 0x9d, 0xa7, 0x6e, 0xd4, 0x84, 0x55, 0xfa, 0x07, 0x1d, 0xfc, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x01, 0x9e, 0x60, 0xf8, 0x5d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MenuServiceClient is the client API for MenuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MenuServiceClient interface {
	// Unary get menu
	GetMenu(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Menu, error)
}

type menuServiceClient struct {
	cc *grpc.ClientConn
}

func NewMenuServiceClient(cc *grpc.ClientConn) MenuServiceClient {
	return &menuServiceClient{cc}
}

func (c *menuServiceClient) GetMenu(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Menu, error) {
	out := new(Menu)
	err := c.cc.Invoke(ctx, "/mookiespb.MenuService/GetMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuServiceServer is the server API for MenuService service.
type MenuServiceServer interface {
	// Unary get menu
	GetMenu(context.Context, *Empty) (*Menu, error)
}

// UnimplementedMenuServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMenuServiceServer struct {
}

func (*UnimplementedMenuServiceServer) GetMenu(ctx context.Context, req *Empty) (*Menu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenu not implemented")
}

func RegisterMenuServiceServer(s *grpc.Server, srv MenuServiceServer) {
	s.RegisterService(&_MenuService_serviceDesc, srv)
}

func _MenuService_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mookiespb.MenuService/GetMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetMenu(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MenuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mookiespb.MenuService",
	HandlerType: (*MenuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenu",
			Handler:    _MenuService_GetMenu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/mookies.proto",
}

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	// Unary
	SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error)
	// completeorder unary
	CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error)
	// server streaming
	SubscribeToOrders(ctx context.Context, in *SubscribeToOrderRequest, opts ...grpc.CallOption) (OrderService_SubscribeToOrdersClient, error)
	// all active orders
	ActiveOrders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrdersResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error) {
	out := new(SubmitOrderResponse)
	err := c.cc.Invoke(ctx, "/mookiespb.OrderService/SubmitOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error) {
	out := new(CompleteOrderResponse)
	err := c.cc.Invoke(ctx, "/mookiespb.OrderService/CompleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) SubscribeToOrders(ctx context.Context, in *SubscribeToOrderRequest, opts ...grpc.CallOption) (OrderService_SubscribeToOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderService_serviceDesc.Streams[0], "/mookiespb.OrderService/SubscribeToOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderServiceSubscribeToOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderService_SubscribeToOrdersClient interface {
	Recv() (*Order, error)
	grpc.ClientStream
}

type orderServiceSubscribeToOrdersClient struct {
	grpc.ClientStream
}

func (x *orderServiceSubscribeToOrdersClient) Recv() (*Order, error) {
	m := new(Order)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderServiceClient) ActiveOrders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/mookiespb.OrderService/ActiveOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	// Unary
	SubmitOrder(context.Context, *SubmitOrderRequest) (*SubmitOrderResponse, error)
	// completeorder unary
	CompleteOrder(context.Context, *CompleteOrderRequest) (*CompleteOrderResponse, error)
	// server streaming
	SubscribeToOrders(*SubscribeToOrderRequest, OrderService_SubscribeToOrdersServer) error
	// all active orders
	ActiveOrders(context.Context, *Empty) (*OrdersResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) SubmitOrder(ctx context.Context, req *SubmitOrderRequest) (*SubmitOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (*UnimplementedOrderServiceServer) CompleteOrder(ctx context.Context, req *CompleteOrderRequest) (*CompleteOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteOrder not implemented")
}
func (*UnimplementedOrderServiceServer) SubscribeToOrders(req *SubscribeToOrderRequest, srv OrderService_SubscribeToOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToOrders not implemented")
}
func (*UnimplementedOrderServiceServer) ActiveOrders(ctx context.Context, req *Empty) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveOrders not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mookiespb.OrderService/SubmitOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).SubmitOrder(ctx, req.(*SubmitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CompleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CompleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mookiespb.OrderService/CompleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CompleteOrder(ctx, req.(*CompleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_SubscribeToOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToOrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServiceServer).SubscribeToOrders(m, &orderServiceSubscribeToOrdersServer{stream})
}

type OrderService_SubscribeToOrdersServer interface {
	Send(*Order) error
	grpc.ServerStream
}

type orderServiceSubscribeToOrdersServer struct {
	grpc.ServerStream
}

func (x *orderServiceSubscribeToOrdersServer) Send(m *Order) error {
	return x.ServerStream.SendMsg(m)
}

func _OrderService_ActiveOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ActiveOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mookiespb.OrderService/ActiveOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ActiveOrders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mookiespb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _OrderService_SubmitOrder_Handler,
		},
		{
			MethodName: "CompleteOrder",
			Handler:    _OrderService_CompleteOrder_Handler,
		},
		{
			MethodName: "ActiveOrders",
			Handler:    _OrderService_ActiveOrders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToOrders",
			Handler:       _OrderService_SubscribeToOrders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protofiles/mookies.proto",
}
