#!/bin/bash

PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
PROTO_FILE="../protofiles/mookies.proto"

cp "${PROTO_FILE}" .

PROTO_FILE="./mookies.proto"

# Directory to write generated code to (.js and .d.ts files)
OUT_DIR="./src/proto"

protoc \
	--plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
	--js_out="import_style=commonjs,binary:${OUT_DIR}" \
	--ts_out="${OUT_DIR}" \
	"${PROTO_FILE}"

rm "${PROTO_FILE}"
