CREATE TABLE IF NOT EXISTS categories (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS items (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	price DECIMAL NOT NULL,
	category_id INTEGER NOT NULL, 
	CONSTRAINT fk_categories
		FOREIGN KEY (category_id)
		REFERENCES categories(id)
);
