INSERT INTO items (name, price, category_id) VALUES ('Large Smoked Pulled Pork', '495', '1');
INSERT INTO items (name, price, category_id) VALUES ('Regular Smoked Pulled Pork', '395', '1');
INSERT INTO items (name, price, category_id) VALUES ('Large Smoked Chicken Breast', '495', '1');
INSERT INTO items (name, price, category_id) VALUES ('Regular Smoked Chicken Breast', '395', '1');
INSERT INTO items (name, price, category_id) VALUES ('The Molly', '395', '1');
INSERT INTO items (name, price, category_id) VALUES ('Large Hamburger', '495', '1');
INSERT INTO items (name, price, category_id) VALUES ('Hamburger', '395', '1');
INSERT INTO items (name, price, category_id) VALUES ('Large Cheeseburger', '550', '1');
INSERT INTO items (name, price, category_id) VALUES ('Cheeseburger', '425', '1');
INSERT INTO items (name, price, category_id) VALUES ('Grilled Cheese', '300', '1');
INSERT INTO items (name, price, category_id) VALUES ('Pulled Pork Melt', '395', '1');
INSERT INTO items (name, price, category_id) VALUES ('Smoked Pulled Pork', '990', '2');
INSERT INTO items (name, price, category_id) VALUES ('Regular Rib', '995', '2');
INSERT INTO items (name, price, category_id) VALUES ('1/2 Smoked Chicken', '995', '2');
INSERT INTO items (name, price, category_id) VALUES ('Smoked Chicken Breast', '725', '2');
INSERT INTO items (name, price, category_id) VALUES ('Smoked Wing (8 wings)', '999', '2');
INSERT INTO items (name, price, category_id) VALUES ('Loaded Nachos (BBQ or Chicken)', '875', '2');
INSERT INTO items (name, price, category_id) VALUES ('Smoked Wing', '500', '3');
INSERT INTO items (name, price, category_id) VALUES ('Rib', '500', '3');
INSERT INTO items (name, price, category_id) VALUES ('Loaded Pork', '899', '4');
INSERT INTO items (name, price, category_id) VALUES ('Loaded Chicken', '899', '4');
INSERT INTO items (name, price, category_id) VALUES ('Loaded Potato (no meat)', '699', '4');
INSERT INTO items (name, price, category_id) VALUES ('Smothered and Covered Fries', '899', '4');
INSERT INTO items (name, price, category_id) VALUES ('Small Cole Slaw', '300', '5');
INSERT INTO items (name, price, category_id) VALUES ('Large Cole Slaw', '600', '5');
INSERT INTO items (name, price, category_id) VALUES ('Small Baked Beans', '300', '5');
INSERT INTO items (name, price, category_id) VALUES ('Large Baked Beans', '600', '5');
INSERT INTO items (name, price, category_id) VALUES ('Small Potato Salad', '300', '5');
INSERT INTO items (name, price, category_id) VALUES ('Large Potato Salad', '600', '5');
INSERT INTO items (name, price, category_id) VALUES ('Plain Chips', '100', '5');
INSERT INTO items (name, price, category_id) VALUES ('Fries', '300', '5');
INSERT INTO items (name, price, category_id) VALUES ('Canned Drink', '100', '6');
INSERT INTO items (name, price, category_id) VALUES ('Bottled Water', '150', '6');
INSERT INTO items (name, price, category_id) VALUES ('Oreo Dream', '350', '7');
INSERT INTO items (name, price, category_id) VALUES ('Lemon Delight', '350', '7');
INSERT INTO items (name, price, category_id) VALUES ('Strawberry Pizza', '350', '7');
INSERT INTO items (name, price, category_id) VALUES ('Whole Dessert', '3000', '7');
INSERT INTO items (name, price, category_id) VALUES ('Small Banana Pudding', '350', '7');
INSERT INTO items (name, price, category_id) VALUES ('Large Banana Pudding', '700', '7');
INSERT INTO items (name, price, category_id) VALUES ('Extra sauce', '50', '8');
