name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        run: |
          PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Staticcheck 
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          make lint

      - name: Run Unit tests.
        run: make test

      - name: Build
        run: make server
